### ISSUE TITLE
Possible secon ARPC with a different set of colors

### ISSUE THREAD

**Issue by dwbarnett** [drunkwinter/MSFS2020.ARPC#1]
Hello, drunkwinter, first of all, Thank You so much for this app.  one of the colorsets that were brought up, were the ones that Mort2end utilized.    Most of us felt they had a more realistic blue look, as well as less green tint.

Would it be to difficult to compile another ARPC version with his values. They are
0.00508    0.00318    0.0

Thank You for your consideration.   I'm not a coder, apologies for bringing this to you.   Hope it's not too difficult to create a secondary version with the above values.   Thank You again for your efforts. Much appreciated.

Sincerely,
David William Barnett

**Comment by drunkwinter** [comment]
Hi, firstly thank you for the kind words. Instead of compiling a second version or potentially many, I'll add an optional configuration file where you can change all this stuff.

Later today I'll maybe have some time to implement this.

**Comment by dwbarnett** [comment]
Thank You. That will be a great addition to your file. Sincerely, David Willing Barnett 

 Sent from AltaMail
 From: drunkwinter < ***@***.*** > Subject: Re: [drunkwinter/MSFS2020.ARPC] Possible secon ARPC with a different set of colors (Issue #1) Date: 10/8/23 03:44 To: "drunkwinter/MSFS2020.ARPC" < ***@***.*** > CC: dwbarnett < ***@***.*** >,  Author < ***@***.*** >

 Hi, firstly thank you for the kind words. Instead of compiling a second version or potentially many, I'll add an optional configuration file where you can change all this stuff.
 Later today I'll maybe have some time to implement this.

**Comment by drunkwinter** [comment]
An `.ini` configuration file was added in [v1.1.0](https://github.com/drunkwinter/MSFS2020.ARPC/releases/tag/v1.1.0)

**Comment by dwbarnett** [comment]
Thank You Sir, much appreciated. Will d/l tomorrow and try parameters. You have given us MSFS 2020 Store versions, at lot less oof a hassle to change sky colors.  As a real world pilot, I can say, that the new parameters or very close to real life now. Thank You Sincerely, David William Barnett 

 Sent from AltaMail
 From: drunkwinter < ***@***.*** > Subject: Re: [drunkwinter/MSFS2020.ARPC] Possible secon ARPC with a different set of colors (Issue #1) Date: 10/8/23 23:43 To: "drunkwinter/MSFS2020.ARPC" < ***@***.*** > CC: dwbarnett < ***@***.*** >,  Author < ***@***.*** >

 An .ini configuration file was added in v1.1.0
