### ISSUE TITLE
Insert Disk

### ISSUE THREAD

**Issue by Vitold69** [drunkwinter/MSFS2020.ARPC#4]
Hello!

My Store Flightsimulator.exe MSFS2020 located at Z:\MSFS 2020\Microsoft Flight Simulator\Content

I have copied all three files to Content directory without any problem.
But when I started MSFS got a message "Please insert the MSFS Game Disc". Removed all three files and simulator starts as usual. Is there any workaround to solve this problem? Thanks

**Comment by drunkwinter** [comment]
What is the size of the MSFS exe in that folder, also what happens when you just paste in `dinput8.dll`?

**Comment by Vitold69** [comment]
Please disregard! It started the second time and later. 
The size of the file is 138 MB (145,006,592 bytes)

What I did is I put two files without ini file and Sim started.
Exit the Sim, added ini file and it started again normally. I can edit and save ini file in the Content directory without problem.

**Comment by drunkwinter** [comment]
Maybe it was a coincidence? 

> The message "Please insert the Microsoft Flight Simulator Game Disc" appears when players are unable to authenticate their game license or when there's a discrepancy between Microsoft accounts.

See https://flightsimulator.zendesk.com/hc/en-us/articles/360015985699--Please-insert-the-Microsoft-Flight-Simulator-Game-Disc-Error-message

But I'm glad it works anyway.

**Comment by Vitold69** [comment]
@drunkwinter 
Thank you very much for help and for excellent program! I believe it will be necessary till the end of MSFS 2020. I have no hope the dumbasses from Asobo solve this issue at all.
