### ISSUE TITLE
Not working for Ms Store version

### ISSUE THREAD

**Issue by alderante** [drunkwinter/MSFS2020.ARPC#5]
Hi, plugin looks great but unfortunately those like me who bought fs from ms store, don't have access to edit the installation folder. Any chance for a workaround or a version that doesn't rely on putting your files directly in that folder? Thanks!

**Comment by drunkwinter** [comment]
Hi, I have the ms store version too. You don't need permissions for the `XboxGames` folder.

As explained in the readme:
> `C:\XboxGames\Microsoft Flight Simulator\Content`
> This folder might not exist if you have an older install, convert to the modern install.
> (See https://parallel42.com/blogs/wiki/converting-my-sim-install-from-legacy-to-modern)

The install size will only be 2gb.
