### ISSUE TITLE
SU 14 problem, mod cant be activated

### ISSUE THREAD

**Issue by SunfishID** [drunkwinter/MSFS2020.ARPC#6]
Hello, when app launched it said the arc thing should be removed. And in game, the mod cant be activated.
![image](https://github.com/drunkwinter/MSFS2020.ARPC/assets/98278433/0ffec8ba-798e-48fd-a312-f7dad705dcfa)

**Comment by drunkwinter** [comment]
Right, that's because the fix is already implemented in Sim Update 14. If you are not on SU14, that means you have a modified executable.
